### ISSUE TITLE
Design  Should be better

### ISSUE THREAD

**Issue by radioblahaj** [ScratchExtensions/scratchextensions.github.io#4]

**Comment by petabyt** [comment]
What do you mean? I think it looks great. How could it be better?

**Comment by radioblahaj** [comment]
Well, It's Very Plain.

**Comment by petabyt** [comment]
What could I add/change to make it look better?

**Comment by radioblahaj** [comment]
Can i have not push acce son this

**Comment by petabyt** [comment]
?

**Comment by radioblahaj** [comment]
i have push access, can i not have it.

**Comment by petabyt** [comment]
ok
